### ISSUE TITLE
Categories do not show up in pretix navigation

### ISSUE THREAD

**Issue by koebi** [pretalx/prtx-faq#2]
Categories are accessible and editable via direct link, but they don't show up in the FAQ navigation bar.
@raphaelm stared at this for a bit and didn't find the problem :)

**Comment by rixx** [comment]
I mean, he added the code, and I just supposed that he knew what he was doing regarding nested navigation in pretix. But since we're using undocumented pretix magic, it being broken is not our fault. I opened a pretix issue (with the three separate issues I ran into), and also fixed the nav.
