### ISSUE TITLE
pretix upgrade to v2023.6.0 fails

### ISSUE THREAD

**Issue by MrGamy** [pretalx/prtx-faq#7]
Cheers rixx,

a customer informed us that the pretix upgrade to [v2023.6.0](https://github.com/pretix/pretix/releases/tag/v2023.6.0) fails when [prtx-faq](https://marketplace.pretix.eu/products/faq/) is installed during the

`python -m pretix migrate/rebuild` commands.

Could you have a look?
[error.log](https://github.com/pretalx/prtx-faq/files/11937915/error.log)

**Comment by rixx** [comment]
Which version are you running? Your error log quotes an import of `ugettext_lazy` that was removed three years ago in 5167179, which was released in 1.0.1. The current version is 1.0.2.
